// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/app/handlers/cardhandlers.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	models "github.com/FischukSergey/gophkeeper/internal/models"
	gomock "github.com/golang/mock/gomock"
)

// MockProtoCardService is a mock of ProtoCardService interface.
type MockProtoCardService struct {
	ctrl     *gomock.Controller
	recorder *MockProtoCardServiceMockRecorder
}

// MockProtoCardServiceMockRecorder is the mock recorder for MockProtoCardService.
type MockProtoCardServiceMockRecorder struct {
	mock *MockProtoCardService
}

// NewMockProtoCardService creates a new mock instance.
func NewMockProtoCardService(ctrl *gomock.Controller) *MockProtoCardService {
	mock := &MockProtoCardService{ctrl: ctrl}
	mock.recorder = &MockProtoCardServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProtoCardService) EXPECT() *MockProtoCardServiceMockRecorder {
	return m.recorder
}

// CardAddMetadata mocks base method.
func (m *MockProtoCardService) CardAddMetadata(ctx context.Context, userID, cardID int64, metadata []models.Metadata) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CardAddMetadata", ctx, userID, cardID, metadata)
	ret0, _ := ret[0].(error)
	return ret0
}

// CardAddMetadataService indicates an expected call of CardAddMetadataService.
func (mr *MockProtoCardServiceMockRecorder) CardAddMetadata(ctx, userID, cardID, metadata interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CardAddMetadata", reflect.TypeOf((*MockProtoCardService)(nil).CardAddMetadata), ctx, userID, cardID, metadata)
}

// CardAdd mocks base method.
func (m *MockProtoCardService) CardAdd(ctx context.Context, card models.Card) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CardAdd", ctx, card)
	ret0, _ := ret[0].(error)
	return ret0
}

// CardAddService indicates an expected call of CardAddService.
func (mr *MockProtoCardServiceMockRecorder) CardAdd(ctx, card interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CardAdd", reflect.TypeOf((*MockProtoCardService)(nil).CardAdd), ctx, card)
}

// CardDelete mocks base method.
func (m *MockProtoCardService) CardDelete(ctx context.Context, cardID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CardDelete", ctx, cardID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CardDeleteService indicates an expected call of CardDeleteService.
func (mr *MockProtoCardServiceMockRecorder) CardDelete(ctx, cardID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CardDelete", reflect.TypeOf((*MockProtoCardService)(nil).CardDelete), ctx, cardID)
}

// CardGetList mocks base method.
func (m *MockProtoCardService) CardGetList(ctx context.Context, userID int64) ([]models.Card, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CardGetList", ctx, userID)
	ret0, _ := ret[0].([]models.Card)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CardGetListService indicates an expected call of CardGetListService.
func (mr *MockProtoCardServiceMockRecorder) CardGetList(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CardGetList", reflect.TypeOf((*MockProtoCardService)(nil).CardGetList), ctx, userID)
}
