// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/app/handlers/notehandler.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	models "github.com/FischukSergey/gophkeeper/internal/models"
	gomock "github.com/golang/mock/gomock"
)

// MockProtoNoteService is a mock of ProtoNoteService interface.
type MockProtoNoteService struct {
	ctrl     *gomock.Controller
	recorder *MockProtoNoteServiceMockRecorder
}

// MockProtoNoteServiceMockRecorder is the mock recorder for MockProtoNoteService.
type MockProtoNoteServiceMockRecorder struct {
	mock *MockProtoNoteService
}

// NewMockProtoNoteService creates a new mock instance.
func NewMockProtoNoteService(ctrl *gomock.Controller) *MockProtoNoteService {
	mock := &MockProtoNoteService{ctrl: ctrl}
	mock.recorder = &MockProtoNoteServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProtoNoteService) EXPECT() *MockProtoNoteServiceMockRecorder {
	return m.recorder
}

// NoteAddService mocks base method.
func (m *MockProtoNoteService) NoteAddService(ctx context.Context, note models.Note) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NoteAddService", ctx, note)
	ret0, _ := ret[0].(error)
	return ret0
}

// NoteAddService indicates an expected call of NoteAddService.
func (mr *MockProtoNoteServiceMockRecorder) NoteAddService(ctx, note interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NoteAddService", reflect.TypeOf((*MockProtoNoteService)(nil).NoteAddService), ctx, note)
}

// NoteDeleteService mocks base method.
func (m *MockProtoNoteService) NoteDeleteService(ctx context.Context, userID, noteID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NoteDeleteService", ctx, userID, noteID)
	ret0, _ := ret[0].(error)
	return ret0
}

// NoteDeleteService indicates an expected call of NoteDeleteService.
func (mr *MockProtoNoteServiceMockRecorder) NoteDeleteService(ctx, userID, noteID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NoteDeleteService", reflect.TypeOf((*MockProtoNoteService)(nil).NoteDeleteService), ctx, userID, noteID)
}

// NoteGetListService mocks base method.
func (m *MockProtoNoteService) NoteGetListService(ctx context.Context, userID int64) ([]models.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NoteGetListService", ctx, userID)
	ret0, _ := ret[0].([]models.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NoteGetListService indicates an expected call of NoteGetListService.
func (mr *MockProtoNoteServiceMockRecorder) NoteGetListService(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NoteGetListService", reflect.TypeOf((*MockProtoNoteService)(nil).NoteGetListService), ctx, userID)
}
