services:
  app:
    image: ${REGISTRY}/${APP_IMAGE_NAME}:latest
    container_name: gophkeeper_app
    ports:
      - "${APP_PORT}:8080"
    environment:
      - DB_HOST=${DB_HOST} # Хост внешней БД Selectel
      - CONFIG_PATH=./config/local.yml
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - PGSSLMODE=require
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_BUCKET=${S3_BUCKET}
    volumes:
      - ./config:/app/config
    restart: unless-stopped
