# grpc server settings
grpc:
  port: 0.0.0.0:8080
  timeout: 10h

# storage settings
postgres:
  dsn: postgres://postgres:postgres@localhost:5432/gophkeeper?sslmode=disable

# log settings
log:
  level: local

# jwt settings
jwt:
  secret_key: 1234567890
  expires_key: 24h

# token ttl
token_ttl: 72h

# s3 settings
s3:
  region: ru-1
  bucket: gophkeeper-bucket
  endpoint: https://s3.ru-1.storage.selcloud.ru
  access_key: e1f0f938e68049dbaa37aec42b0d8c84
  secret_key: 02006774199d4233bc10f47130ceae82
  force_path_style: true
