# grpc server settings
grpc:
  port: localhost:8080
  timeout: 10h

# storage settings
postgres:
  dsn: postgres://postgres:postgres@localhost:5432/gophkeeper?sslmode=disable

# log settings
log:
  level: local

# jwt settings
jwt:
  secret_key: 1234567890
  expires_key: 1h

# token ttl
token_ttl: 72h
