name: Deploy to Selectel

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  REGISTRY: cr.selcloud.ru
  APP_IMAGE_NAME: gophkeeper/app
  DB_IMAGE_NAME: gophkeeper/db

jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
      
  #     - name: Set up Go
  #       uses: actions/setup-go@v4
  #       with:
  #         go-version: '1.22'
          
  #     - name: Run tests
  #       run: go test -v -count=1 ./internal/app/... ./internal/client/... ./internal/lib/...

  build-and-push:
#    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.SELECTEL_TOKEN_NAME }}
          password: ${{ secrets.SELECTEL_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push App image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./build/app.Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ env.REGISTRY }}/${{ env.APP_IMAGE_NAME }}:latest
            #${REGISTRY}/${APP_IMAGE_NAME}:${{ github.sha }}

      - name: Build and push DB image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./build/db/db.Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ env.REGISTRY }}/${{ env.DB_IMAGE_NAME }}:latest
            #${REGISTRY}/${DB_IMAGE_NAME}:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Copy docker-compose file to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SELECTEL_HOST }}
          username: ${{ secrets.SELECTEL_SSH_USER }}
          key: ${{ secrets.SELECTEL_SSH_KEY }}
          source: "./docker-compose.prod.yaml,./config/local.yml"
          #strip_components: 0
          target: "/root/app"

      - name: Deploy to Selectel Cloud
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SELECTEL_HOST }}
          username: ${{ secrets.SELECTEL_SSH_USER }}
          key: ${{ secrets.SELECTEL_SSH_KEY }}
          script: |
            cd /root/app
            docker login ${{ env.REGISTRY }} -u ${{ secrets.SELECTEL_TOKEN_NAME }} -p ${{ secrets.SELECTEL_TOKEN }}
            docker pull ${{ env.REGISTRY }}/${{ env.APP_IMAGE_NAME }}:latest
            docker pull ${{ env.REGISTRY }}/${{ env.DB_IMAGE_NAME }}:latest
            # Graceful shutdown
            docker-compose -f docker-compose.prod.yaml down --timeout 60
            # Clear any remaining volumes if needed
            docker volume rm gophkeeper_postgres_data || true
            docker-compose -f docker-compose.prod.yaml up --force-recreate -d
