name: Deploy to Selectel

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  REGISTRY: cr.selcloud.ru
  APP_IMAGE_NAME: gophkeeper-app
  DB_IMAGE_NAME: gophkeeper-db

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
          
      - name: Run tests
        run: go test -v -count=1 ./internal/app/... ./internal/client/... ./internal/lib/...

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      - uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Login to Selectel Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.SELECTEL_USERNAME }}
          password: ${{ secrets.SELECTEL_PASSWORD }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push App image
        uses: docker/build-push-action@v5
        with:
          context: ./build/app
          file: ./build/app.Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.REGISTRY }}/${{ secrets.SELECTEL_PROJECT_ID }}/${{ env.APP_IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ secrets.SELECTEL_PROJECT_ID }}/${{ env.APP_IMAGE_NAME }}:${{ github.sha }}

      - name: Build and push DB image
        uses: docker/build-push-action@v5
        with:
          context: ./build/db
          file: ./build/docker-compose.db.yaml
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.REGISTRY }}/${{ secrets.SELECTEL_PROJECT_ID }}/${{ env.DB_IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ secrets.SELECTEL_PROJECT_ID }}/${{ env.DB_IMAGE_NAME }}:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Copy docker-compose file to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SELECTEL_HOST }}
          username: ${{ secrets.SELECTEL_SSH_USER }}
          key: ${{ secrets.SELECTEL_SSH_KEY }}
          source: "docker-compose.prod.yaml,.env"
          target: "/root/app"

      - name: Deploy to Selectel Cloud
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SELECTEL_HOST }}
          username: ${{ secrets.SELECTEL_SSH_USER }}
          key: ${{ secrets.SELECTEL_SSH_KEY }}
          script: |
            cd /root/app
            docker login ${{ env.REGISTRY }} -u ${{ secrets.SELECTEL_USERNAME }} -p ${{ secrets.SELECTEL_PASSWORD }}
            docker pull ${{ env.REGISTRY }}/${{ secrets.SELECTEL_PROJECT_ID }}/${{ env.APP_IMAGE_NAME }}:latest
            docker pull ${{ env.REGISTRY }}/${{ secrets.SELECTEL_PROJECT_ID }}/${{ env.DB_IMAGE_NAME }}:latest
            docker-compose -f docker-compose.prod.yaml down
            docker-compose -f docker-compose.prod.yaml up -d
