name: Deploy to Selectel

on:
  workflow_dispatch:

env:
  REGISTRY: cr.selcloud.ru
  APP_IMAGE_NAME: gophkeeper-app
  DB_IMAGE_NAME: gophkeeper-db

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
          
      - name: Run tests
        run: go test -v -count=1 ./internal/app/... ./internal/client/... ./internal/lib/...

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Selectel Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}  #регистр контейнеров
          username: ${{ secrets.SELECTEL_USERNAME }}  #имя пользователя в облаке
          password: ${{ secrets.SELECTEL_PASSWORD }}  #пароль пользователя в облаке

      - name: Build and push App image
        uses: docker/build-push-action@v5
        with:
          context: ./build/app
          file: ./build/app.Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ secrets.SELECTEL_PROJECT_ID }}/${{ env.APP_IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ secrets.SELECTEL_PROJECT_ID }}/${{ env.APP_IMAGE_NAME }}:${{ github.sha }}

      - name: Build and push DB image
        uses: docker/build-push-action@v5
        with:
          context: ./build/db
          file: ./build/docker-compose.db.yaml
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ secrets.SELECTEL_PROJECT_ID }}/${{ env.DB_IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ secrets.SELECTEL_PROJECT_ID }}/${{ env.DB_IMAGE_NAME }}:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Selectel Cloud
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SELECTEL_HOST }}  #ip адрес облака
          username: ${{ secrets.SELECTEL_SSH_USER }}  #имя пользователя для подключения по ssh
          key: ${{ secrets.SELECTEL_SSH_KEY }}  #ключ пользователя для подключения по ssh
          script: |
            docker login ${{ env.REGISTRY }} -u ${{ secrets.SELECTEL_USERNAME }} -p ${{ secrets.SELECTEL_PASSWORD }}  #логинимся в облаке
            docker pull ${{ env.REGISTRY }}/${{ secrets.SELECTEL_PROJECT_ID }}/${{ env.APP_IMAGE_NAME }}:latest  #скачиваем последнюю версию приложения
            docker pull ${{ env.REGISTRY }}/${{ secrets.SELECTEL_PROJECT_ID }}/${{ env.DB_IMAGE_NAME }}:latest  #скачиваем последнюю версию базы данных
            docker-compose -f docker-compose.prod.yaml down  #останавливаем контейнеры
            docker-compose -f docker-compose.prod.yaml up -d  #запускаем контейнеры
